# Generated by Django 4.2.23 on 2025-08-08 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Candidato",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        default="Não informado",
                        max_length=100,
                        verbose_name="Nome Completo",
                    ),
                ),
                ("sexo", models.CharField(default="Não informado", max_length=20)),
                ("cep", models.CharField(blank=True, max_length=9, null=True)),
                (
                    "endereco",
                    models.CharField(
                        default="Não informado", max_length=255, verbose_name="Endereço"
                    ),
                ),
                ("bairro", models.CharField(default="Não informado", max_length=100)),
                ("cidade", models.CharField(default="Não informado", max_length=100)),
                (
                    "tempo_residencia",
                    models.CharField(
                        default="Não informado",
                        max_length=50,
                        verbose_name="Quanto tempo reside no último endereço?",
                    ),
                ),
                ("contato", models.CharField(default="Não informado", max_length=50)),
                ("idade", models.IntegerField(default=0)),
                (
                    "estado_civil",
                    models.CharField(default="Não informado", max_length=50),
                ),
                (
                    "tem_filhos",
                    models.BooleanField(default=False, verbose_name="Tem filhos?"),
                ),
                (
                    "qtd_filhos",
                    models.IntegerField(
                        blank=True,
                        default=None,
                        null=True,
                        verbose_name="Quantos filhos?",
                    ),
                ),
                (
                    "idade_filhos",
                    models.CharField(
                        blank=True,
                        default=None,
                        max_length=100,
                        null=True,
                        verbose_name="Idade dos filhos?",
                    ),
                ),
                (
                    "mora_com_filhos",
                    models.BooleanField(
                        default=False, verbose_name="Mora com os filhos?"
                    ),
                ),
                ("moradia", models.CharField(default="Não informado", max_length=50)),
                (
                    "meio_locomocao",
                    models.CharField(default="Não informado", max_length=100),
                ),
                (
                    "habitos",
                    models.CharField(
                        default="Nenhum", max_length=200, verbose_name="Hábitos"
                    ),
                ),
                (
                    "preferencia_cargo",
                    models.CharField(
                        default="Não informado",
                        max_length=100,
                        verbose_name="Preferência de cargo",
                    ),
                ),
                (
                    "preferencia_turno",
                    models.CharField(
                        default="Não informado",
                        max_length=50,
                        verbose_name="Preferência de turno",
                    ),
                ),
                (
                    "melhor_trabalho",
                    models.TextField(
                        blank=True,
                        default="",
                        verbose_name="Qual foi o trabalho que você mais gostou, teve o melhor desempenho e mais se destacou?",
                    ),
                ),
                (
                    "pontos_fortes",
                    models.TextField(
                        blank=True,
                        default="",
                        verbose_name="No que você se considera bom?",
                    ),
                ),
                (
                    "lazer",
                    models.TextField(
                        blank=True,
                        default="",
                        verbose_name="O que você mais gosta de fazer nas horas vagas?",
                    ),
                ),
                (
                    "objetivo_curto_prazo",
                    models.TextField(
                        blank=True,
                        default="",
                        verbose_name="Quais são seus objetivos pessoais a curto prazo",
                    ),
                ),
                (
                    "objetivo_longo_prazo",
                    models.TextField(
                        blank=True,
                        default="",
                        verbose_name="Quais são seus objetivos pessoais a longo prazo",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        default="nao.informado@exemplo.com", max_length=254
                    ),
                ),
                (
                    "curriculo",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="curriculos/",
                        verbose_name="Currículo",
                    ),
                ),
                (
                    "total_i",
                    models.IntegerField(default=0, verbose_name="Total 'I' (Águia)"),
                ),
                (
                    "total_c",
                    models.IntegerField(default=0, verbose_name="Total 'C' (Gato)"),
                ),
                (
                    "total_a",
                    models.IntegerField(default=0, verbose_name="Total 'A' (Tubarão)"),
                ),
                (
                    "total_o",
                    models.IntegerField(default=0, verbose_name="Total 'O' (Lobo)"),
                ),
                (
                    "perfil_comportamental",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Perfil Comportamental",
                    ),
                ),
                (
                    "contratado",
                    models.BooleanField(
                        default=False, verbose_name="Já foi contratado?"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Empresa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(max_length=100, verbose_name="Nome da Empresa"),
                ),
                (
                    "logotipo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="logotipos/",
                        verbose_name="Logotipo",
                    ),
                ),
                (
                    "descricao",
                    models.TextField(
                        blank=True, null=True, verbose_name="Sobre a Empresa"
                    ),
                ),
            ],
            options={
                "verbose_name": "Empresa",
                "verbose_name_plural": "Empresas",
            },
        ),
        migrations.CreateModel(
            name="Pergunta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "texto",
                    models.CharField(max_length=255, verbose_name="Texto da Pergunta"),
                ),
                (
                    "alternativa_i",
                    models.CharField(
                        max_length=255, verbose_name="Alternativa (I - Águia)"
                    ),
                ),
                (
                    "alternativa_c",
                    models.CharField(
                        max_length=255, verbose_name="Alternativa (C - Gato)"
                    ),
                ),
                (
                    "alternativa_a",
                    models.CharField(
                        max_length=255, verbose_name="Alternativa (A - Tubarão)"
                    ),
                ),
                (
                    "alternativa_o",
                    models.CharField(
                        max_length=255, verbose_name="Alternativa (O - Lobo)"
                    ),
                ),
                ("ativo", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Vaga",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=100)),
                ("descricao", models.TextField()),
                ("requisitos", models.TextField()),
                (
                    "turno",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Diurno", "Diurno"),
                            ("Noturno", "Noturno"),
                            ("Qualquer", "Qualquer Turno"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "tipo_cargo",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Garçom", "Garçom"),
                            ("Cumim", "Cumim"),
                            ("Caixa", "Caixa"),
                            ("Bartender", "Bartender"),
                            ("Montagem de lanche", "Montagem de lanche"),
                            ("Cozinheiro", "Cozinheiro"),
                            ("Chapeiro", "Chapeiro"),
                            ("Auxiliar de cozinha", "Auxiliar de cozinha"),
                            ("Auxiliar de limpeza", "Auxiliar de limpeza"),
                            ("Serviços gerais", "Serviços gerais"),
                            ("Freelancer", "Freelancer"),
                        ],
                        max_length=100,
                        null=True,
                    ),
                ),
                ("data_criacao", models.DateTimeField(auto_now_add=True)),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vagas",
                        to="vagas.empresa",
                        verbose_name="Empresa",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Inscricao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_inscricao", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("recebida", "Recebida"),
                            ("em_analise", "Em Análise"),
                            ("entrevista", "Entrevista Agendada"),
                            ("aprovado", "Aprovado"),
                            ("rejeitado", "Rejeitado"),
                        ],
                        default="recebida",
                        max_length=20,
                        verbose_name="Status da Candidatura",
                    ),
                ),
                (
                    "notas_internas",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="Notas Internas do Recrutador",
                    ),
                ),
                (
                    "candidato",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vagas.candidato",
                    ),
                ),
                (
                    "vaga",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="vagas.vaga"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RespostaCandidato",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "perfil_escolhido",
                    models.CharField(
                        choices=[("I", "I"), ("C", "C"), ("A", "A"), ("O", "O")],
                        max_length=1,
                        verbose_name="Perfil Escolhido",
                    ),
                ),
                (
                    "candidato",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vagas.candidato",
                    ),
                ),
                (
                    "pergunta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="vagas.pergunta"
                    ),
                ),
            ],
            options={
                "unique_together": {("candidato", "pergunta")},
            },
        ),
        migrations.CreateModel(
            name="Funcionario",
            fields=[
                (
                    "perfil_candidato",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="vagas.candidato",
                    ),
                ),
                ("cargo", models.CharField(max_length=100)),
                ("data_admissao", models.DateField(auto_now_add=True)),
                ("data_demissao", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ativo", "Ativo"),
                            ("demitido", "Demitido"),
                            ("lista_negra", "Lista Negra"),
                        ],
                        default="ativo",
                        max_length=20,
                    ),
                ),
                (
                    "observacoes",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="Observações (ex: motivo da demissão)",
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="vagas.empresa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Funcionário",
                "verbose_name_plural": "Funcionários",
            },
        ),
        migrations.CreateModel(
            name="FuncionarioAtivo",
            fields=[],
            options={
                "verbose_name": "Funcionário Ativo",
                "verbose_name_plural": "Funcionários Ativos",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("vagas.funcionario",),
        ),
        migrations.CreateModel(
            name="FuncionarioDemitido",
            fields=[],
            options={
                "verbose_name": "Funcionário Demitido",
                "verbose_name_plural": "Funcionários Demitidos",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("vagas.funcionario",),
        ),
        migrations.CreateModel(
            name="FuncionarioListaNegra",
            fields=[],
            options={
                "verbose_name": "Funcionário em Lista Negra",
                "verbose_name_plural": "Funcionários em Lista Negra",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("vagas.funcionario",),
        ),
    ]
