# Generated by Django 4.2.23 on 2025-08-03 21:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Candidato",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(default="Não informado", max_length=100)),
                ("sexo", models.CharField(default="Não informado", max_length=20)),
                ("endereco", models.CharField(default="Não informado", max_length=255)),
                ("bairro", models.CharField(default="Não informado", max_length=100)),
                ("cidade", models.CharField(default="Não informado", max_length=100)),
                (
                    "tempo_residencia",
                    models.CharField(default="Não informado", max_length=50),
                ),
                ("contato", models.CharField(default="Não informado", max_length=50)),
                ("idade", models.IntegerField(default=0)),
                (
                    "estado_civil",
                    models.CharField(default="Não informado", max_length=50),
                ),
                ("tem_filhos", models.BooleanField(default=False)),
                (
                    "qtd_filhos",
                    models.IntegerField(blank=True, default=None, null=True),
                ),
                (
                    "idade_filhos",
                    models.CharField(
                        blank=True, default=None, max_length=100, null=True
                    ),
                ),
                ("mora_com_filhos", models.BooleanField(default=False)),
                ("moradia", models.CharField(default="Não informado", max_length=50)),
                (
                    "meio_locomocao",
                    models.CharField(default="Não informado", max_length=100),
                ),
                ("habitos", models.CharField(default="Nenhum", max_length=200)),
                (
                    "preferencia_cargo",
                    models.CharField(default="Não informado", max_length=100),
                ),
                (
                    "preferencia_turno",
                    models.CharField(default="Não informado", max_length=50),
                ),
                ("melhor_trabalho", models.TextField(blank=True, default="")),
                ("pontos_fortes", models.TextField(blank=True, default="")),
                ("lazer", models.TextField(blank=True, default="")),
                ("objetivo_curto_prazo", models.TextField(blank=True, default="")),
                ("objetivo_longo_prazo", models.TextField(blank=True, default="")),
                (
                    "email",
                    models.EmailField(
                        default="nao.informado@exemplo.com", max_length=254
                    ),
                ),
                (
                    "curriculo",
                    models.FileField(blank=True, null=True, upload_to="curriculos/"),
                ),
                (
                    "total_i",
                    models.IntegerField(default=0, verbose_name="Total 'I' (Águia)"),
                ),
                (
                    "total_c",
                    models.IntegerField(default=0, verbose_name="Total 'C' (Gato)"),
                ),
                (
                    "total_a",
                    models.IntegerField(default=0, verbose_name="Total 'A' (Tubarão)"),
                ),
                (
                    "total_o",
                    models.IntegerField(default=0, verbose_name="Total 'O' (Lobo)"),
                ),
                (
                    "perfil_comportamental",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Perfil Comportamental",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Pergunta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "texto",
                    models.CharField(max_length=255, verbose_name="Texto da Pergunta"),
                ),
                (
                    "alternativa_i",
                    models.CharField(
                        max_length=255, verbose_name="Alternativa (I - Águia)"
                    ),
                ),
                (
                    "alternativa_c",
                    models.CharField(
                        max_length=255, verbose_name="Alternativa (C - Gato)"
                    ),
                ),
                (
                    "alternativa_a",
                    models.CharField(
                        max_length=255, verbose_name="Alternativa (A - Tubarão)"
                    ),
                ),
                (
                    "alternativa_o",
                    models.CharField(
                        max_length=255, verbose_name="Alternativa (O - Lobo)"
                    ),
                ),
                ("ativo", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Vaga",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=100)),
                ("descricao", models.TextField()),
                ("requisitos", models.TextField()),
                ("data_criacao", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Inscricao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_inscricao", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("recebida", "Recebida"),
                            ("em_analise", "Em Análise"),
                            ("entrevista", "Entrevista Agendada"),
                            ("aprovado", "Aprovado"),
                            ("rejeitado", "Rejeitado"),
                        ],
                        default="recebida",
                        max_length=20,
                        verbose_name="Status da Candidatura",
                    ),
                ),
                (
                    "notas_internas",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="Notas Internas do Recrutador",
                    ),
                ),
                (
                    "candidato",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vagas.candidato",
                    ),
                ),
                (
                    "vaga",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="vagas.vaga"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RespostaCandidato",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "perfil_escolhido",
                    models.CharField(
                        choices=[("I", "I"), ("C", "C"), ("A", "A"), ("O", "O")],
                        max_length=1,
                        verbose_name="Perfil Escolhido",
                    ),
                ),
                (
                    "candidato",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vagas.candidato",
                    ),
                ),
                (
                    "pergunta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="vagas.pergunta"
                    ),
                ),
            ],
            options={
                "unique_together": {("candidato", "pergunta")},
            },
        ),
    ]
