# Generated by Django 4.2.23 on 2025-08-09 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vagas", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="empresa",
            options={
                "ordering": ["ordem"],
                "verbose_name": "Empresa",
                "verbose_name_plural": "Empresas",
            },
        ),
        migrations.AddField(
            model_name="empresa",
            name="ordem",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Ordem de Exibição"
            ),
        ),
    ]
