# Generated by Django 4.2.23 on 2025-08-04 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("vagas", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Empresa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(max_length=100, verbose_name="Nome da Empresa"),
                ),
                (
                    "logotipo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="logotipos/",
                        verbose_name="Logotipo",
                    ),
                ),
                (
                    "descricao",
                    models.TextField(
                        blank=True, null=True, verbose_name="Sobre a Empresa"
                    ),
                ),
            ],
            options={
                "verbose_name": "Empresa",
                "verbose_name_plural": "Empresas",
            },
        ),
        migrations.AddField(
            model_name="vaga",
            name="tipo_cargo",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Garçom", "Garçom"),
                    ("Cozinha", "Cozinha"),
                    ("Caixa", "Caixa"),
                    ("Serviços gerais", "Serviços gerais"),
                    ("Freelancer", "Freelancer"),
                ],
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="vaga",
            name="turno",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Diurno", "Diurno"),
                    ("Noturno", "Noturno"),
                    ("Qualquer", "Qualquer Turno"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="vaga",
            name="empresa",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="vagas",
                to="vagas.empresa",
                verbose_name="Empresa",
            ),
            preserve_default=False,
        ),
    ]
