# Generated by Django 4.2.23 on 2025-08-12 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vagas", "0002_alter_empresa_options_empresa_ordem"),
    ]

    operations = [
        migrations.DeleteModel(
            name="FuncionarioListaNegra",
        ),
        migrations.CreateModel(
            name="FuncionarioComObservacao",
            fields=[],
            options={
                "verbose_name": "Funcionário Com Observação",
                "verbose_name_plural": "Funcionários com Observação",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("vagas.funcionario",),
        ),
        migrations.AlterField(
            model_name="funcionario",
            name="status",
            field=models.CharField(
                choices=[
                    ("ativo", "Ativo"),
                    ("demitido", "Demitido"),
                    ("observacao", "Com Observação"),
                ],
                default="ativo",
                max_length=20,
            ),
        ),
    ]
