# Generated by Django 4.2.23 on 2025-08-05 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vagas", "0003_alter_vaga_tipo_cargo"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidato",
            name="cep",
            field=models.CharField(blank=True, default="Não informado", max_length=9),
        ),
    ]
