# Generated by Django 4.2.23 on 2025-08-13 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vagas", "0003_delete_funcionariolistanegra_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="funcionario",
            options={
                "verbose_name": "Funcionário",
                "verbose_name_plural": "Funcionários (Todos)",
            },
        ),
        migrations.AlterModelOptions(
            name="funcionariocomobservacao",
            options={
                "verbose_name": "Funcionário com Observação",
                "verbose_name_plural": "Funcionários com Observação",
            },
        ),
        migrations.AddField(
            model_name="candidato",
            name="cpf",
            field=models.CharField(
                blank=True, max_length=14, null=True, unique=True, verbose_name="CPF"
            ),
        ),
        migrations.AddField(
            model_name="funcionario",
            name="remuneracao",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="candidato",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name="candidato",
            name="melhor_trabalho",
            field=models.TextField(
                blank=True,
                default="",
                verbose_name="Qual foi o trabalho que você mais gostou...",
            ),
        ),
        migrations.AlterField(
            model_name="candidato",
            name="nome",
            field=models.CharField(max_length=100, verbose_name="Nome Completo"),
        ),
        migrations.AlterField(
            model_name="funcionario",
            name="data_admissao",
            field=models.DateField(),
        ),
    ]
