# Generated by Django 4.2.23 on 2025-08-05 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vagas", "0004_candidato_cep"),
    ]

    operations = [
        migrations.AlterField(
            model_name="candidato",
            name="tempo_residencia",
            field=models.CharField(
                default="Não informado", max_length=50, verbose_name="Você tem filhos?"
            ),
        ),
    ]
