# Generated by Django 4.2.23 on 2025-08-16 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vagas", "0004_alter_funcionario_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="candidato",
            name="contato",
            field=models.CharField(
                max_length=50, verbose_name="Celular (com Whatsapp)"
            ),
        ),
        migrations.AlterField(
            model_name="candidato",
            name="meio_locomocao",
            field=models.CharField(
                default="Não informado",
                max_length=100,
                verbose_name="Meio de locomoção",
            ),
        ),
    ]
