# Generated by Django 4.2.23 on 2025-08-16 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vagas", "0005_alter_candidato_contato_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="inscricao",
            name="data_entrevista",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Data e Hora da Entrevista"
            ),
        ),
        migrations.AlterField(
            model_name="candidato",
            name="contato",
            field=models.CharField(
                max_length=50, verbose_name="Celular (com Whatsapp e DDD)"
            ),
        ),
    ]
