# Generated by Django 4.2.23 on 2025-08-05 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vagas", "0006_alter_candidato_tempo_residencia"),
    ]

    operations = [
        migrations.AlterField(
            model_name="candidato",
            name="curriculo",
            field=models.FileField(
                blank=True, null=True, upload_to="curriculos/", verbose_name="Currículo"
            ),
        ),
        migrations.AlterField(
            model_name="candidato",
            name="endereco",
            field=models.CharField(
                default="Não informado", max_length=255, verbose_name="Endereço"
            ),
        ),
        migrations.AlterField(
            model_name="candidato",
            name="habitos",
            field=models.CharField(
                default="Nenhum", max_length=200, verbose_name="Hábitos"
            ),
        ),
        migrations.AlterField(
            model_name="candidato",
            name="idade_filhos",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=100,
                null=True,
                verbose_name="Idade dos filhos?",
            ),
        ),
        migrations.AlterField(
            model_name="candidato",
            name="lazer",
            field=models.TextField(
                blank=True,
                default="",
                verbose_name="O que você mais gosta de fazer nas horas vagas?",
            ),
        ),
        migrations.AlterField(
            model_name="candidato",
            name="melhor_trabalho",
            field=models.TextField(
                blank=True,
                default="",
                verbose_name="Qual foi o trabalho que você mais gostou, teve o melhor desempenho e mais se destacou?",
            ),
        ),
        migrations.AlterField(
            model_name="candidato",
            name="mora_com_filhos",
            field=models.BooleanField(
                default=False, verbose_name="Mora com os filhos?"
            ),
        ),
        migrations.AlterField(
            model_name="candidato",
            name="nome",
            field=models.CharField(
                default="Não informado", max_length=100, verbose_name="Nome Completo"
            ),
        ),
        migrations.AlterField(
            model_name="candidato",
            name="objetivo_curto_prazo",
            field=models.TextField(
                blank=True,
                default="",
                verbose_name="Quais são seus objetivos pessoais a curto prazo",
            ),
        ),
        migrations.AlterField(
            model_name="candidato",
            name="objetivo_longo_prazo",
            field=models.TextField(
                blank=True,
                default="",
                verbose_name="Quais são seus objetivos pessoais a longo prazo",
            ),
        ),
        migrations.AlterField(
            model_name="candidato",
            name="pontos_fortes",
            field=models.TextField(
                blank=True, default="", verbose_name="No que você se considera bom?"
            ),
        ),
        migrations.AlterField(
            model_name="candidato",
            name="preferencia_cargo",
            field=models.CharField(
                default="Não informado",
                max_length=100,
                verbose_name="Preferência de cargo",
            ),
        ),
        migrations.AlterField(
            model_name="candidato",
            name="preferencia_turno",
            field=models.CharField(
                default="Não informado",
                max_length=50,
                verbose_name="Preferência de turno",
            ),
        ),
        migrations.AlterField(
            model_name="candidato",
            name="qtd_filhos",
            field=models.IntegerField(
                blank=True, default=None, null=True, verbose_name="Quantos filhos?"
            ),
        ),
        migrations.AlterField(
            model_name="candidato",
            name="tem_filhos",
            field=models.BooleanField(default=False, verbose_name="Tem filhos?"),
        ),
        migrations.AlterField(
            model_name="candidato",
            name="tempo_residencia",
            field=models.CharField(
                default="Não informado",
                max_length=50,
                verbose_name="Quanto tempo reside no último endereço?",
            ),
        ),
    ]
