# Generated by Django 4.2.23 on 2025-08-17 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vagas", "0006_inscricao_data_entrevista_alter_candidato_contato"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inscricao",
            name="status",
            field=models.CharField(
                choices=[
                    ("incompleto", "Incompleto"),
                    ("recebida", "Recebida"),
                    ("em_analise", "Em Análise"),
                    ("entrevista", "Entrevista Agendada"),
                    ("aprovado", "Aprovado"),
                    ("rejeitado", "Rejeitado"),
                ],
                default="incompleto",
                max_length=20,
                verbose_name="Status da Candidatura",
            ),
        ),
    ]
