# Generated by Django 4.2.23 on 2025-08-18 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vagas", "0007_alter_inscricao_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cargo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "ordering": ["nome"],
            },
        ),
    ]
