# Generated by Django 4.2.23 on 2025-08-08 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("vagas", "0007_alter_candidato_curriculo_alter_candidato_endereco_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidato",
            name="contratado",
            field=models.BooleanField(default=False, verbose_name="Já foi contratado?"),
        ),
        migrations.AlterField(
            model_name="candidato",
            name="cep",
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
        migrations.CreateModel(
            name="Funcionario",
            fields=[
                (
                    "perfil_candidato",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="vagas.candidato",
                    ),
                ),
                ("cargo", models.CharField(max_length=100)),
                ("data_admissao", models.DateField(auto_now_add=True)),
                ("data_demissao", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ativo", "Ativo"),
                            ("demitido", "Demitido"),
                            ("lista_negra", "Lista Negra"),
                        ],
                        default="ativo",
                        max_length=20,
                    ),
                ),
                (
                    "observacoes",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="Observações (ex: motivo da demissão)",
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="vagas.empresa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Funcionário",
                "verbose_name_plural": "Funcionários",
            },
        ),
    ]
