# Generated by Django 4.2.23 on 2025-08-20 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vagas", "0008_cargo"),
    ]

    operations = [
        migrations.AddField(
            model_name="funcionario",
            name="data_direito_ferias",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="funcionario",
            name="data_fim_experiencia_30_30",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="funcionario",
            name="data_fim_experiencia_45_45",
            field=models.DateField(blank=True, null=True),
        ),
    ]
