# Generated by Django 4.2.23 on 2025-08-08 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vagas", "0008_candidato_contratado_alter_candidato_cep_funcionario"),
    ]

    operations = [
        migrations.CreateModel(
            name="FuncionarioAtivo",
            fields=[],
            options={
                "verbose_name": "Funcionário Ativo",
                "verbose_name_plural": "Funcionários Ativos",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("vagas.funcionario",),
        ),
        migrations.CreateModel(
            name="FuncionarioDemitido",
            fields=[],
            options={
                "verbose_name": "Funcionário Demitido",
                "verbose_name_plural": "Funcionários Demitidos",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("vagas.funcionario",),
        ),
        migrations.CreateModel(
            name="FuncionarioListaNegra",
            fields=[],
            options={
                "verbose_name": "Funcionário em Lista Negra",
                "verbose_name_plural": "Funcionários em Lista Negra",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("vagas.funcionario",),
        ),
    ]
