# Generated by Django 4.2.23 on 2025-08-21 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vagas", "0009_funcionario_data_direito_ferias_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="funcionario",
            name="data_fim_experiencia_30_30",
        ),
        migrations.RemoveField(
            model_name="funcionario",
            name="data_fim_experiencia_45_45",
        ),
        migrations.AddField(
            model_name="funcionario",
            name="data_fim_experiencia",
            field=models.DateField(
                blank=True,
                editable=False,
                null=True,
                verbose_name="Data Final da Experiência",
            ),
        ),
        migrations.AddField(
            model_name="funcionario",
            name="tipo_experiencia",
            field=models.CharField(
                blank=True,
                choices=[
                    ("30_60", "30 + 30 dias (60 dias)"),
                    ("45_90", "45 + 45 dias (90 dias)"),
                ],
                max_length=5,
                null=True,
                verbose_name="Tipo de Contrato de Experiência",
            ),
        ),
    ]
