# Generated by Django 4.2.23 on 2025-08-21 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vagas", "0010_remove_funcionario_data_fim_experiencia_30_30_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="funcionario",
            name="data_fim_gozo_ferias",
            field=models.DateField(
                blank=True, null=True, verbose_name="Fim do Gozo de Férias"
            ),
        ),
        migrations.AddField(
            model_name="funcionario",
            name="data_inicio_gozo_ferias",
            field=models.DateField(
                blank=True, null=True, verbose_name="Início do Gozo de Férias"
            ),
        ),
    ]
