# Generated by Django 4.2.23 on 2025-08-21 17:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("vagas", "0011_funcionario_data_fim_gozo_ferias_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricoFuncionario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_ocorrencia", models.DateTimeField(auto_now_add=True)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("AUTOMATICO", "Automático"),
                            ("OBSERVACAO", "Observação"),
                            ("FALTA", "Falta / Advertência"),
                            ("ELOGIO", "Elogio / Promoção"),
                        ],
                        default="OBSERVACAO",
                        max_length=20,
                    ),
                ),
                ("descricao", models.TextField(verbose_name="Descrição do Evento")),
                (
                    "criado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "funcionario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historico",
                        to="vagas.funcionario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Registro de Histórico",
                "verbose_name_plural": "Registros de Histórico",
                "ordering": ["-data_ocorrencia"],
            },
        ),
    ]
