# Generated by Django 4.2.23 on 2025-08-21 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vagas", "0012_historicofuncionario"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicofuncionario",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("ELOGIO", "Elogio / Reconhecimento"),
                    ("FEEDBACK", "Feedback / Alinhamento"),
                    ("TREINAMENTO", "Treinamento / Capacitação"),
                    ("PROMOCAO", "Promoção / Aumento"),
                    ("ALTERACAO_CONTRATUAL", "Alteração Contratual"),
                    ("ATESTADO", "Apresentação de Atestado"),
                    ("ADVERTENCIA", "Advertência (Verbal ou Escrita)"),
                    ("FALTA_ATRASO", "Falta / Atraso"),
                    ("OCORRENCIA_OP", "Ocorrência Operacional"),
                    ("RECLAMACAO_CLIENTE", "Reclamação de Cliente"),
                    ("OBSERVACAO", "Observação Geral"),
                ],
                default="OBSERVACAO",
                max_length=20,
            ),
        ),
    ]
