# Generated by Django 4.2.23 on 2025-09-01 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vagas", "0014_perfilgerente"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="inscricao",
            options={"verbose_name": "Inscrição", "verbose_name_plural": "Inscrições"},
        ),
        migrations.AlterField(
            model_name="candidato",
            name="email",
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name="inscricao",
            name="status",
            field=models.CharField(
                choices=[
                    ("incompleto", "Incompleto"),
                    ("recebida", "Recebida"),
                    ("em_analise", "Em Análise"),
                    ("entrevista", "Entrevista Agendada"),
                    ("aprovado", "Aprovado"),
                    ("aguardando_documentacao", "Aguardando Documentação"),
                    ("rejeitado", "Rejeitado"),
                ],
                default="incompleto",
                max_length=30,
                verbose_name="Status da Candidatura",
            ),
        ),
    ]
