# Generated by Django 4.2.23 on 2025-09-01 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vagas", "0015_alter_inscricao_options_alter_candidato_email_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="vaga",
            name="numero_vagas",
            field=models.IntegerField(default=1, verbose_name="Número de Vagas"),
        ),
    ]
