# Generated by Django 4.2.23 on 2025-09-02 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vagas", "0016_vaga_numero_vagas"),
    ]

    operations = [
        migrations.AddField(
            model_name="vaga",
            name="ativo",
            field=models.BooleanField(default=True, verbose_name="Vaga Ativa"),
        ),
    ]
