# Generated by Django 4.2.23 on 2025-09-03 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vagas", "0017_vaga_ativo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vaga",
            name="tipo_cargo",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Garçom", "Garçom"),
                    ("Cumim", "Cumim"),
                    ("Caixa", "Caixa"),
                    ("Bartender", "Bartender"),
                    ("Montagem de lanche", "Montagem de lanche"),
                    ("Cozinheiro", "Cozinheiro"),
                    ("Chapeiro", "Chapeiro"),
                    ("Auxiliar de cozinha", "Auxiliar de cozinha"),
                    ("Auxiliar de limpeza", "Auxiliar de limpeza"),
                    ("Serviços gerais", "Serviços gerais"),
                    ("Freelancer", "Freelancer"),
                    ("instrutor_funcional", "Instrutor(a) de Treinamento Funcional"),
                    ("estagiario", "Estagiário"),
                ],
                max_length=100,
                null=True,
            ),
        ),
    ]
