# Generated by Django 4.2.23 on 2025-09-08 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vagas", "0019_remove_inscricao_notas_internas_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="candidato",
            name="notas_internas",
            field=models.TextField(
                blank=True, null=True, verbose_name="Notas Internas do Recrutador"
            ),
        ),
        migrations.AlterField(
            model_name="vaga",
            name="tipo_cargo",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Garçom", "Garçom"),
                    ("Cumim", "Cumim"),
                    ("Caixa", "Caixa"),
                    ("Bartender", "Bartender"),
                    ("Montagem de lanche", "Montagem de lanche"),
                    ("Cozinheiro", "Cozinheiro"),
                    ("Chapeiro", "Chapeiro"),
                    ("Auxiliar de cozinha", "Auxiliar de cozinha"),
                    ("Auxiliar de limpeza", "Auxiliar de limpeza"),
                    ("Freelancer", "Freelancer"),
                    ("instrutor_funcional", "Instrutor(a) de Treinamento Funcional"),
                    ("estagiario", "Estagiário"),
                ],
                max_length=100,
                null=True,
            ),
        ),
    ]
