# Generated by Django 4.2.23 on 2025-09-10 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("vagas", "0020_alter_candidato_notas_internas_alter_vaga_tipo_cargo"),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentoFuncionario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "titulo",
                    models.CharField(
                        max_length=100, verbose_name="Título ou Descrição do Documento"
                    ),
                ),
                (
                    "tipo_documento",
                    models.CharField(
                        choices=[
                            ("FOLHA_PONTO", "Folha Ponto"),
                            ("CONTRATO", "Contrato de Trabalho"),
                            ("RG_CPF", "Documento de Identidade (RG/CPF)"),
                            ("COMP_RESIDENCIA", "Comprovante de Residência"),
                            ("ATESTADO_MEDICO", "Atestado Médico"),
                            ("FERIAS", "Recibo de Férias"),
                            ("DECIMO_TERCEIRO", "Recibo de 13º Salário"),
                            ("OUTROS", "Outros"),
                        ],
                        default="OUTROS",
                        max_length=20,
                        verbose_name="Tipo de Documento",
                    ),
                ),
                (
                    "arquivo",
                    models.FileField(
                        upload_to="documentos_funcionarios/%Y/%m/",
                        verbose_name="Arquivo",
                    ),
                ),
                (
                    "data_upload",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Upload"
                    ),
                ),
                (
                    "funcionario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documentos",
                        to="vagas.funcionario",
                        verbose_name="Funcionário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Documento de Funcionário",
                "verbose_name_plural": "Documentos de Funcionários",
                "ordering": ["-data_upload"],
            },
        ),
    ]
