# Generated by Django 4.2.23 on 2025-09-15 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vagas', '0021_documentofuncionario'), # Garanta que este é o nome da sua última migração
    ]

    operations = [
        migrations.AlterField(
            model_name='candidato',
            name='notas_internas',
            field=models.TextField(blank=True, null=True, verbose_name='Notas Internas do Recrutador'),
        ),
    ]