# Generated by Django 4.2.23 on 2025-10-20 12:43

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("vagas", "0022_corrige_notas_internas"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vaga",
            name="tipo_cargo",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Garçom", "Garçom"),
                    ("Cumim", "Cumim"),
                    ("Caixa", "Caixa"),
                    ("Bartender", "Bartender"),
                    ("Montagem de lanche", "Montagem de lanche"),
                    ("Cozinheiro", "Cozinheiro"),
                    ("Chapeiro", "Chapeiro"),
                    ("Auxiliar de cozinha", "Auxiliar de cozinha"),
                    ("Auxiliar de limpeza", "Auxiliar de limpeza"),
                    ("Freelancer", "Freelancer"),
                    ("instrutor_funcional", "Instrutor(a) de Treinamento Funcional"),
                    ("estagiario", "Estagiário"),
                    ("administrativo", "administrativo"),
                ],
                max_length=100,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="EntregaUniforme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "item",
                    models.CharField(max_length=255, verbose_name="Item do Uniforme"),
                ),
                (
                    "quantidade",
                    models.PositiveIntegerField(default=1, verbose_name="Quantidade"),
                ),
                (
                    "data_entrega",
                    models.DateField(
                        default=django.utils.timezone.now,
                        verbose_name="Data de Entrega",
                    ),
                ),
                (
                    "data_devolucao",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data de Devolução"
                    ),
                ),
                (
                    "termo_compromisso",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="termos_uniforme/",
                        verbose_name="Termo de Compromisso Assinado",
                    ),
                ),
                (
                    "observacoes",
                    models.TextField(blank=True, null=True, verbose_name="Observações"),
                ),
                (
                    "funcionario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="uniformes_entregues",
                        to="vagas.funcionario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Entrega de Uniforme",
                "verbose_name_plural": "Entregas de Uniforme",
                "ordering": ["-data_entrega"],
            },
        ),
    ]
