# Generated by Django 4.2.23 on 2025-11-16 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("vagas", "0023_alter_vaga_tipo_cargo_entregauniforme"),
    ]

    operations = [
        migrations.CreateModel(
            name="ManualEmpresa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "titulo",
                    models.CharField(max_length=200, verbose_name="Título do Manual"),
                ),
                (
                    "categoria",
                    models.CharField(
                        choices=[
                            ("OPERACIONAL", "Operacional (Cozinha, Atendimento)"),
                            ("RH", "Recursos Humanos (Conduta, Uniforme)"),
                            ("ADM", "Administrativo / Financeiro"),
                            ("OUTROS", "Outros"),
                        ],
                        default="OPERACIONAL",
                        max_length=50,
                        verbose_name="Categoria",
                    ),
                ),
                (
                    "arquivo",
                    models.FileField(
                        upload_to="manuais_empresa/",
                        verbose_name="Arquivo (PDF, Word, etc.)",
                    ),
                ),
                (
                    "data_atualizacao",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última Atualização"
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        blank=True,
                        help_text="Se deixar em branco, este manual será visível para TODAS as empresas.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="vagas.empresa",
                        verbose_name="Específico da Empresa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Manual da Empresa",
                "verbose_name_plural": "Manuais da Empresa",
                "ordering": ["-data_atualizacao"],
            },
        ),
    ]
